[filters]
symbols = [
    "String::*",
    "OsStr::*",
    "Cow::*",
    "PathBuf::*",
    "Vec::*",
    "Error::*",
    "*::into",
    "*::is_some",
    "Some",
    "Ok",
    "clone",
    "*::is_mut",
    "*::is_ref",
    "Option::*",
    "Result::*",
    "into",
    "str::*"
]
